"""removed_is_active from User

Revision ID: a0627f8aab78
Revises: ae23171f9002
Create Date: 2025-08-31 22:49:21.419199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0627f8aab78'
down_revision: Union[str, Sequence[str], None] = 'ae23171f9002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
