"""unique constraint is added in company

Revision ID: b40f4e9a30bf
Revises: a0627f8aab78
Create Date: 2025-09-01 02:14:45.602550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b40f4e9a30bf'
down_revision: Union[str, Sequence[str], None] = 'a0627f8aab78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies') as batch_op:
        batch_op.create_unique_constraint('uq_company_name', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    # ### end Alembic commands ###
